Make component
kangddong/My-iOS-Scratch-papaer pull request #2
Opened 2023-07-07 07:54 UTC by kangddong

2023-07-10 05:37 UTC, Rhode-park requested changes
`tag`를 사용하여 버튼을 구분하고, currentTab의 상태를 변경하는게 참신하고 논리적으로 보였습니다. RX님의 코드 중 가장 인상 깊은 부분이었던 것 같습니다.

코드가 정말 배울 점이 많아서 UI적인 부분 말고는 리뷰를 드릴 수가 없겠네요🥲 제 리뷰가 조금이나마 도움이 되었으면 좋겠습니다.

그리고 코드를 보면서 저도 많은 것을 배워갑니다🙂

2023-07-10 05:37 UTC, Rhode-park commented on UIKit/refactoringCustomTabView/refactoringCustomTabView/TwoButtonTabComponent.swift
> +        button.titleLabel?.font = UIFont.systemFont(ofSize: 16)
`systemFont(ofSize:)`를 사용하신 이유가 있으실까요? [systemfont에 대한 문서](https://developer.apple.com/documentation/uikit/uifont/1619027-systemfont)를 살펴보시면 다음과 같은 내용이 나와있네요.
> it’s often more appropriate to use `preferredFont(forTextStyle:)` because that method respects the user’s selected content size category.

2023-07-10 05:37 UTC, Rhode-park commented on UIKit/refactoringCustomTabView/refactoringCustomTabView/TwoButtonTabComponent.swift
> +
private func에 대해서는 개행을 한 번 하는게 RX님의 컨벤션일까요? public func나 init에서는 맨 윗줄 개행이 없는데, 의도하신 부분인지 궁금합니다.

2023-07-10 05:37 UTC, Rhode-park commented on UIKit/refactoringCustomTabView/refactoringCustomTabView/TwoButtonTabComponent.swift
> +        alignment = .fill
마찬가지입니다. default value가 무엇일까요?

2023-07-10 05:37 UTC, Rhode-park commented on UIKit/refactoringCustomTabView/refactoringCustomTabView/TwoButtonTabComponent.swift
> +        distribution = .fill
[UIStackView/Distribution](https://developer.apple.com/documentation/uikit/uistackview/1616233-distribution)문서를 참고해보시겠어요?
> The default value is UIStackView.Distribution.fill.

라는 말이 있네요!

2023-07-10 05:37 UTC, Rhode-park commented on UIKit/refactoringCustomTabView/refactoringCustomTabView/TwoButtonTabComponent.swift
> +        stackView.spacing = 0
이 부분도 [공식문서](https://developer.apple.com/documentation/uikit/uistackview/1616225-spacing)를 살펴보면 좋을 것 같습니다. 

> The default value is 0.0.

라는 말이 있네요?

2023-07-10 05:37 UTC, Rhode-park commented on UIKit/refactoringCustomTabView/refactoringCustomTabView/TwoButtonTabComponent.swift
> +        spacing = 0
위의 stackView와 마찬가지로 spacing에 대한 공식문서 참고해보심이 좋을 것 같습니다!

2023-07-24 03:35 UTC, kangddong commented on UIKit/refactoringCustomTabView/refactoringCustomTabView/TwoButtonTabComponent.swift
> +
아핫 많이 질문을 받았는데 저만의 컨벤션인거같아요 ㅜㅜ ㅋㅋ
혹시 애플에서 Swift 컨벤션을 명확하게 정한게 있나요 ?? 제가 알기로는 없어가지구...
이전에 C언어 style에서 괄호 스타일만 Swift로 바뀌면서 그렇게 된거같아요 ㅋㅋㅋ 

`class`, `extension,` `func` 키워드 다음 줄은 꼭 한줄 띄어서 구분감 의도인데, nested 한 느낌이 싫더라구여 ㅜㅜㅋㅋ
init은 super.init까지 한 세트라서 그 다음 줄이 개행하고 ... 
public은 제 규칙을 제가 어긴 녀석이네요 ...

``` c
int main(void)
{
    printf("hello wolrd")
}
```

``` swift
func printText() {

    printf("hello wolrd")
}
```

2023-07-24 03:35 UTC, kangddong commented on UIKit/refactoringCustomTabView/refactoringCustomTabView/TwoButtonTabComponent.swift
> +        button.titleLabel?.font = UIFont.systemFont(ofSize: 16)
`systemFont(ofSize:)`를 습관적으로 사용했었을뿐인데, `preferredFont(forTextStyle:)` 는 몰랐어요 !
기존에 `systemFont(ofSize:)` 사용하면서 다이내믹하지않은게 고민이었던 것도 같이 해결됐구요 !
쓰임새에 대해서 디자이너랑 얘기를 해봐야할거같아요 !! ㅎㅎ 감사합니다.

2023-07-24 03:35 UTC, kangddong commented on UIKit/refactoringCustomTabView/refactoringCustomTabView/TwoButtonTabComponent.swift
> +        stackView.axis = .horizontal
오 default value에 대해서 리뷰해주셨군요 감사합니다 !! 
매번 프로퍼티를 외우기도 힘들고, 명시적으로 작성이 되어있지않으면 까먹기도해서
명시적으로 표기를 해보았는데, 보통은 default value와 같은 값은 표시를 안할까요 ?

2023-07-24 03:41 UTC, kangddong commented
@Rhode-park 로데 꼼꼼하게 리뷰 해줘서 정말 고마워요 !
항상 다른 사람은 내 코드를 어떻게 봐줄까 의도가 명확하게 들어날까 ? 고민을 많이하는데 
리뷰 덕에 제가 궁금했던 부분들이 많이 해소된거같아요 !!

2023-07-26 05:02 UTC, Rhode-park commented on UIKit/refactoringCustomTabView/refactoringCustomTabView/TwoButtonTabComponent.swift
> +        stackView.axis = .horizontal
제 개인적인 생각입니다만, default value에 대해서는 미리 숙지가 되어있어야하고 굳이 코드를 통해 나타낼 필요가 없어보입니다.

2023-07-26 05:03 UTC, Rhode-park commented on UIKit/refactoringCustomTabView/refactoringCustomTabView/TwoButtonTabComponent.swift
> +
컨벤션을 명확히 정한게 있다기보다는, 일관성이 없어서 여쭤봤습니다!

2023-07-26 08:30 UTC, merged